# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 02:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessingrequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageprocessingrequest',
            options={'ordering': ('created',)},
        ),
        migrations.RemoveField(
            model_name='imageprocessingrequest',
            name='requestid',
        ),
        migrations.AddField(
            model_name='imageprocessingrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
